server:
  port: 8084
  
#datasource configuration  
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ecommerce_order_detail?createDatabaseIfNotExist=true
    username: root
    password: Harry@01
    driver-class-name: com.mysql.cj.jdbc.Driver
   
  # jpa configuration 
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
    show-sql: true
  
  application:
    name: ecommerce-order-service
   
# dailect spring boot can auto detects, but we can set here also
    
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
    